export const quiz = {
  quizTitle: "SVM Quiz",
  quizSynopsis: "This is a short quiz to test your understanding",
  nrOfQuestions: "4",
  questions: [
    // {
    //   question:
    //     "How can you access the state of a component from inside of a member function?",
    //   questionType: "text",
    //   questionPic: "https://dummyimage.com/600x400/000/fff&text=X", // if you need to display Picture in Question
    //   answerSelectionType: "single",
    //   answers: [
    //     "this.getState()",
    //     "this.prototype.stateValue",
    //     "this.state",
    //     "this.values",
    //   ],
    //   correctAnswer: "3",
    //   messageForCorrectAnswer: "Correct answer. Good job.",
    //   messageForIncorrectAnswer: "Incorrect answer. Please try again.",
    //   explanation:
    //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //   point: "20",
    // },
    {
      question: "SVC implementation is based on _____?",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["libsvm", "SGDRegressor"],
      correctAnswer: "1",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation: "SVC implementation is based on libsvm.",
      point: "10",
    },
    {
      question: "Is Linear a type of SVM kernel?",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["True", "False"],
      correctAnswer: "1",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation: "Linear kernel is a type of SVM kernel.",
      point: "10",
    },
    {
      question: "Which of the following concepts is/are SVM kernels?",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["Linear", "RBF", "Sigmoid", "Polynomial", "All of the above"],
      correctAnswer: "5",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation:
        "Linear, RBF, Sigmoid and Polynomial are the different kernels used in SVM.",
      point: "30",
    },
    {
      question: "What are the two models under SVM?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "SVM and SVC",
        "SVC and SVD",
        "SGD and SVR",
        "SVB and SVC",
        "SVC and SVR",
      ],
      correctAnswer: "5",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation: "SVC and SVR are the two models under SVM.",
      point: "30",
    },
    // {
    //   question: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
    //   questionType: "photo",
    //   answerSelectionType: "single",
    //   answers: [
    //     "https://dummyimage.com/600x400/000/fff&text=A",
    //     "https://dummyimage.com/600x400/000/fff&text=B",
    //     "https://dummyimage.com/600x400/000/fff&text=C",
    //     "https://dummyimage.com/600x400/000/fff&text=D",
    //   ],
    //   correctAnswer: "1",
    //   messageForCorrectAnswer: "Correct answer. Good job.",
    //   messageForIncorrectAnswer: "Incorrect answer. Please try again.",
    //   explanation:
    //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //   point: "20",
    // },
    // {
    //   question: "What are the advantages of React JS?",
    //   questionType: "text",
    //   answerSelectionType: "multiple",
    //   answers: [
    //     "React can be used on client and as well as server side too",
    //     "Using React increases readability and makes maintainability easier. Component, Data patterns improves readability and thus makes it easier for manitaining larger apps",
    //     "React components have lifecycle events that fall into State/Property Updates",
    //     "React can be used with any other framework (Backbone.js, Angular.js) as it is only a view layer",
    //   ],
    //   correctAnswer: [1, 2, 4],
    //   messageForCorrectAnswer: "Correct answer. Good job.",
    //   messageForIncorrectAnswer: "Incorrect answer. Please try again.",
    //   explanation:
    //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    //   point: "20",
    // },
  ],
};
